# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Python course
# week 1
# Noam Hirsch
# 302346259

import pandas as pd

my_csv = {"subject_id": [1, 2, 3, 4, 5, 6],
          "gender": ["female", "male", "male", "male", "female", "male"],
"age": [28, 29, 33, 19, 23, 31],
          "depression": [1, 0, 1, 1, 0, 0]}

df = pd.DataFrame(my_csv) df.to_csv("/Users/noam/Desktop/python/lessons/assigment_1.csv")